"""add location.fingerprint + offer.categories/tags

Revision ID: 3a9b98359d65
Revises: 05ec8873b987
Create Date: 2025-09-07 22:41:06.221760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9b98359d65'
down_revision = '05ec8873b987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fingerprint', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_locations_city'))
        batch_op.drop_index(batch_op.f('ix_locations_postal_code'))
        batch_op.create_index(batch_op.f('ix_locations_fingerprint'), ['fingerprint'], unique=True)
        batch_op.drop_column('street')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('country')

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('source', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('source_url', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('dt_start', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('dt_end', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('price_value', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_offers_title'))
        batch_op.create_index(batch_op.f('ix_offers_dt_start'), ['dt_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_external_id'), ['external_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_external_id'))
        batch_op.drop_index(batch_op.f('ix_offers_dt_start'))
        batch_op.create_index(batch_op.f('ix_offers_title'), ['title'], unique=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('image')
        batch_op.drop_column('price_value')
        batch_op.drop_column('dt_end')
        batch_op.drop_column('dt_start')
        batch_op.drop_column('source_url')
        batch_op.drop_column('source')
        batch_op.drop_column('external_id')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=2), server_default=sa.text("'DE'::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('street', sa.VARCHAR(length=160), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_locations_fingerprint'))
        batch_op.create_index(batch_op.f('ix_locations_postal_code'), ['postal_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_city'), ['city'], unique=False)
        batch_op.drop_column('address')
        batch_op.drop_column('fingerprint')

    # ### end Alembic commands ###
