"""empty message

Revision ID: 752c3a430414
Revises: b7041ef0bc7c
Create Date: 2025-12-09 10:30:50.042066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752c3a430414'
down_revision = 'b7041ef0bc7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_required', sa.Boolean(), server_default='false', nullable=True))
        batch_op.add_column(sa.Column('registration_methods', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('registration_contact', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('recurrence_rule', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_column('recurrence_rule')
        batch_op.drop_column('registration_contact')
        batch_op.drop_column('registration_methods')
        batch_op.drop_column('registration_required')

    # ### end Alembic commands ###
