"""empty message

Revision ID: 9c137fb0165c
Revises: 
Create Date: 2025-12-06 15:59:13.787561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c137fb0165c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)

    op.create_table('community_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=160), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=40), server_default='feedback', nullable=False),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='new', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_fingerprint'), ['fingerprint'], unique=True)

    op.create_table('organizers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('organisation_type', sa.String(length=80), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizers_slug'), ['slug'], unique=True)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('firstname', sa.String(length=80), nullable=True),
    sa.Column('lastname', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('is_premium', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('premium_until', sa.DateTime(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('summary', sa.String(length=400), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('dt_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dt_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='EUR', nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('event', 'community', 'permanent', name='offer_type'), server_default='event', nullable=False),
    sa.Column('opening_hours', sa.JSON(), nullable=True),
    sa.Column('holiday_hours', sa.JSON(), nullable=True),
    sa.Column('maps_url', sa.String(length=500), nullable=True),
    sa.Column('meeting_point', sa.String(length=200), nullable=True),
    sa.Column('is_outdoor', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_indoor', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('target_age_min', sa.Integer(), nullable=True),
    sa.Column('target_age_max', sa.Integer(), nullable=True),
    sa.Column('with_accompaniment', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_free', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('hobby_regular', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_once', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('is_sporty', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_creative', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('pets_allowed', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('source_name', sa.String(length=120), nullable=True),
    sa.Column('source_type', sa.Enum('manual', 'crawler', 'ocr', name='source_type'), server_default='manual', nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='offer_status'), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('organizer_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('recurring_series_id', sa.UUID(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organizers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index('idx_offers_dates', ['dt_start', 'dt_end'], unique=False)
        batch_op.create_index('idx_offers_filters', ['is_free', 'is_outdoor', 'is_sporty', 'is_creative', 'pets_allowed'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_dt_start'), ['dt_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_offers_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_title'), ['title'], unique=False)

    op.create_table('organisation_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organizers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'slug', name='uq_organisation_folder_slug')
    )
    op.create_table('organisation_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('confirmation_message', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organizers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'slug', name='uq_organisation_form_slug')
    )
    op.create_table('organisation_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organizers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'slug', name='uq_organisation_group_slug')
    )
    op.create_table('organisation_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=50), server_default='organisation_admin', nullable=False),
    sa.Column('token', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('invited_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organizers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('organisation_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organisation_invitations_email'), ['email'], unique=False)

    op.create_table('organisation_users',
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), server_default='organisation_admin', nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organizers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organisation_id', 'user_id')
    )
    op.create_table('user_children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_children', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_children_user_id'), ['user_id'], unique=False)

    op.create_table('offer_categories',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offer_id', 'category_id')
    )
    op.create_table('offer_tags',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offer_id', 'tag_id')
    )
    op.create_table('organisation_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('folder', sa.String(length=160), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.Enum('internal', 'public', name='document_visibility'), server_default='internal', nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['organisation_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organizers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organisation_form_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('field_type', sa.String(length=50), server_default='text', nullable=False),
    sa.Column('required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['organisation_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organisation_form_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('participant_name', sa.String(length=200), nullable=True),
    sa.Column('participant_email', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['form_id'], ['organisation_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organisation_group_members',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), server_default='organisation_admin', nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['organisation_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_table('organisation_group_offers',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['organisation_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'offer_id')
    )
    op.create_table('user_favorite_offers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'offer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorite_offers')
    op.drop_table('organisation_group_offers')
    op.drop_table('organisation_group_members')
    op.drop_table('organisation_form_submissions')
    op.drop_table('organisation_form_fields')
    op.drop_table('organisation_documents')
    op.drop_table('offer_tags')
    op.drop_table('offer_categories')
    with op.batch_alter_table('user_children', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_children_user_id'))

    op.drop_table('user_children')
    op.drop_table('organisation_users')
    with op.batch_alter_table('organisation_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organisation_invitations_email'))

    op.drop_table('organisation_invitations')
    op.drop_table('organisation_groups')
    op.drop_table('organisation_forms')
    op.drop_table('organisation_folders')
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_title'))
        batch_op.drop_index(batch_op.f('ix_offers_organisation_id'))
        batch_op.drop_index(batch_op.f('ix_offers_location_id'))
        batch_op.drop_index(batch_op.f('ix_offers_external_id'))
        batch_op.drop_index(batch_op.f('ix_offers_dt_start'))
        batch_op.drop_index('idx_offers_filters')
        batch_op.drop_index('idx_offers_dates')

    op.drop_table('offers')
    op.drop_table('users')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))

    op.drop_table('tags')
    with op.batch_alter_table('organizers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizers_slug'))

    op.drop_table('organizers')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_fingerprint'))

    op.drop_table('locations')
    op.drop_table('community_feedback')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_slug'))

    op.drop_table('categories')
    # ### end Alembic commands ###
