"""add user profile fields and dashboard tables

Revision ID: 9dde0df6addc
Revises: 2a1d95de8884
Create Date: 2025-12-01 11:54:59.753781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dde0df6addc'
down_revision = '2a1d95de8884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_children', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_children_user_id'), ['user_id'], unique=False)

    op.create_table('user_favorite_offers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'offer_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), server_default='false', nullable=True))
        batch_op.add_column(sa.Column('premium_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('preferences', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferences')
        batch_op.drop_column('premium_until')
        batch_op.drop_column('is_premium')
        batch_op.drop_column('profile_image')
        batch_op.drop_column('city')
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    op.drop_table('user_favorite_offers')
    with op.batch_alter_table('user_children', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_children_user_id'))

    op.drop_table('user_children')
    # ### end Alembic commands ###
