name: Build, Push & Migrate

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push API
        uses: docker/build-push-action@v5
        with:
          context: ./apps/api
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/lottina-api:dev
            ghcr.io/${{ github.repository_owner }}/lottina-api:${{ github.sha }}

      - name: Build & Push Worker
        uses: docker/build-push-action@v5
        with:
          context: ./apps/worker
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/lottina-worker:dev
            ghcr.io/${{ github.repository_owner }}/lottina-worker:${{ github.sha }}

  migrate:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          cd apps/api
          pip install -r requirements.txt

      - name: Run Alembic migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          cd apps/api
          alembic upgrade head
