name: Build & Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # wichtig für GHCR push

    env:
      REGISTRY: ghcr.io
      IMAGE_NAMESPACE: ${{ github.repository_owner }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push API
        uses: docker/build-push-action@v4
        with:
          context: ./apps/api
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/lottina-api:dev
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/lottina-api:${{ github.sha }}
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}

      - name: Build & Push Worker
        uses: docker/build-push-action@v4
        with:
          context: ./apps/worker
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/lottina-worker:dev
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/lottina-worker:${{ github.sha }}
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
